# Default values for angular-spring-heroes.

replicaCount: 1

image:
  repository: porscheinformatik/angular-spring-heroes
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  # host: fullhostname.example.com
  # basename: example.com

postgresql:
  enabled: false
  postgresUser: heroes
  postgresDatabase: heroes

resources:
  limits:
   cpu: 700m
   memory: 768Mi
  requests:
   cpu: 200m
   memory: 256Mi
