image:
  repository: docker.porscheinformatik.com/koc/angular-spring-heroes
  tag: master
postgresql:
  enabled: true
  postgresUser: heroes
  postgresDatabase: heroes
  persistence:
    storageClass: thin-csi
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 20m
    memory: 480Mi
datadog:
  apm:
    enabled: true
  application: angular-spring-heroes
  component: app
  enabled: true
  env: qa
  team: fcs-cto-eenv
env:
  - name: DD_LOGS_INJECTION
    value: 'true'
  - name: DD_PROFILING_ENABLED
    value: 'true'
